service: my-nestjs-serverless-backend
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  memorySize: 256
  timeout: 6
plugins:
  - serverless-plugin-warmup-ts-bridge-v2
  - serverless-plugin-typescript
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 3000
functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true